### ISSUE TITLE
Production Instructions (i.e. Digital Ocean)

### ISSUE THREAD

**Issue by alteredorange** [TwilioDevEd/call-tracking-laravel#17]
Hey guys,

This looks like exactly what I'm looking for, but I'm not to clear on setup instructions.  I'd love to get this set up on a Digital Ocean droplet, is that possible?  Or is this just meant to run locally?

Thanks!

**Comment by joliveros** [comment]
Hi @alteredorange,

You should be able to [ set this up in DO](https://www.cloudways.com/blog/install-laravel-on-digitalocean/). The instructions are the same except for the proxy part. Instead of ngrok you would need to expose your app on port 80 and be sure your domain points to your droplets' public ip. Finally, you should be able to point all necessary webhooks in your Twilio Console to point to your host.

for instance, you would use:

`http://your-domain.com/lead`

instead of:

`http://fjaoijaf.ngrok.com/lead`

Best,

José

**Comment by alteredorange** [comment]
Okay, after a long night I think I'm close...  I've got an apache server, the postgres database, and everything else seems to be set up right.  I just did the "php artisan migrate" and it said migration table created successfully.  The only thing is, the site still just shows the directory:  
![image](https://cloud.githubusercontent.com/assets/2141012/22725568/7fd0e7ca-ed8b-11e6-80d8-6479c1714cb4.png)

and if I go to /dashboard, I get:
![image](https://cloud.githubusercontent.com/assets/2141012/22725584/90a98174-ed8b-11e6-9bc4-731d3308f320.png)

Any idea what I'm doing wrong?  Sorry, I'm not very good at this stuff, it's taken me a while just to get this far :)

**Comment by alteredorange** [comment]
Woo hoo, I got everything working! Now one more question :)  So it's just the charts, right?  There's no way to drill in on the actual campaigns (and see what numbers called), or do any sort of export?  If I ran lots of campaigns the chart might get kind of hard to read.
